#!/bin/bash

set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

sandbox="$(make_sandbox)"
sandboxes=("$sandbox")
trap 'rm -rf "${sandboxes[@]}"' EXIT

# A few of the newer tests below need a clean, isolated pending/timer state
# rather than the one this file keeps building up above; give them their own.
new_sandbox() {
  local dir
  dir="$(make_sandbox "$@")"
  sandboxes+=("$dir")
  echo "$dir"
}

# ---- state
state="$(run_cli "$sandbox" state)"
jq -e . <<<"$state" >/dev/null || fail "state is valid JSON" "$state"
assert_eq "$(jq -r '.displays | length' <<<"$state")" "2" "state lists both displays"
assert_eq "$(jq -r .focused <<<"$state")" "DP-1" "focused display reported"
assert_eq "$(jq -r '.displays[0].live.bitdepth' <<<"$state")" "8" "bitdepth derived from format"
assert_eq "$(jq -r '.displays[0].capabilities.supportsHdr' <<<"$state")" "true" "capabilities attached"
assert_eq "$(jq -r '.displays[0].brightness' <<<"$state")" "62" "brightness attached to focused display"
assert_eq "$(jq -r '.displays[1].brightness' <<<"$state")" "null" "brightness only read for focused display"
assert_eq "$(jq -r .pending <<<"$state")" "null" "nothing pending initially"
assert_eq "$(jq -r .global.cm_auto_hdr <<<"$state")" "1" "global auto-hdr read"
pass "state"

# ---- apply with timer
out="$(run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}')"
assert_contains "$out" "pending" "apply reports pending"
[[ -s $sandbox/state/pending.json ]] || fail "pending file written"
eval_chunk="$(cat "$sandbox/eval-last.txt")"
[[ $(head -1 "$sandbox/eval-last.txt") == hl.* ]] || fail "live chunk starts with a statement, not the file header" "$(head -1 "$sandbox/eval-last.txt")"
assert_not_contains "$eval_chunk" "-- " "live chunk carries no comments"
assert_contains "$eval_chunk" 'output = "DP-1", disabled = false, mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0' "untouched display declared explicitly"
assert_contains "$eval_chunk" 'output = "DP-2", disabled = false, mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 203' "changed display carries colour fields"
assert_contains "$(cat "$sandbox/systemd-run.log")" "revert --expired" "revert timer armed"
[[ ! -e $sandbox/state/candela-layout.lua ]] || fail "layout not persisted before keep"
pass "apply arms the timer and declares every display"

# ---- state while pending
state="$(run_cli "$sandbox" state)"
assert_eq "$(jq -r '.pending | type' <<<"$state")" "object" "state exposes pending"
assert_eq "$(jq -r '.displays[1].pendingConfig.cm' <<<"$state")" "hdr" "pending config attached per display"
pass "pending state"

# ---- chained apply keeps earlier pending fields
run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","sdr_max_luminance":250}]}' >/dev/null
eval_chunk="$(cat "$sandbox/eval-last.txt")"
assert_contains "$eval_chunk" 'cm = "hdr", sdr_max_luminance = 250' "chained apply merges onto pending"
pass "chained apply"

# ---- keep
: > "$sandbox/hyprctl.log"
out="$(run_cli "$sandbox" keep)"
assert_eq "$out" "kept" "keep reports kept"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after keep"
lua="$(cat "$sandbox/state/candela-layout.lua")"
assert_contains "$lua" "Generated by io.github.pushmotta.candela" "layout header"
assert_contains "$lua" 'hl.monitor({ output = "DP-2", disabled = false, mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 250 })' "layout carries kept fields"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", disabled = false, mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0 })' "layout declares the other display"
assert_eq "$(jq -r '.displays["DP-2"].cm' "$sandbox/state/intent.json")" "hdr" "intent persisted"
assert_contains "$(cat "$sandbox/hyprctl.log")" "reload" "keep reloads"
pass "keep persists intent and layout"

# ---- revert drops pending and reloads
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
out="$(run_cli "$sandbox" revert)"
assert_eq "$out" "reverted" "revert reports"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after revert"
assert_eq "$(jq -r '.displays["DP-1"].scale // "none"' "$sandbox/state/intent.json")" "none" "reverted change not in intent"
pass "revert"

# ---- the timer's own revert must not stop its own service before cleaning up
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
token="$(jq -r '.token' "$sandbox/state/pending.json")"
: > "$sandbox/systemctl.log"
out="$(run_cli "$sandbox" revert --expired --token "$token")"
assert_eq "$out" "reverted" "expired revert reports"
[[ ! -e $sandbox/state/pending.json ]] || fail "expired revert clears pending"
assert_not_contains "$(cat "$sandbox/systemctl.log")" "stop" "expired revert does not stop its own unit"
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
: > "$sandbox/systemctl.log"
run_cli "$sandbox" revert >/dev/null
assert_contains "$(cat "$sandbox/systemctl.log")" "stop omarchy-candela-revert.timer" "interactive revert cancels the timer"
pass "expired revert survives its own timer unit"

# ---- apply --now persists immediately
out="$(run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-2","sdr_max_luminance":203}]}')"
assert_eq "$out" "kept" "apply --now keeps"
assert_eq "$(jq -r '.displays["DP-2"].sdr_max_luminance' "$sandbox/state/intent.json")" "203" "apply --now persisted"
pass "apply --now"

# ---- validation
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","cm":"bogus"}]}' 2>/dev/null; then fail "bad cm rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2;x","bitdepth":10}]}' 2>/dev/null; then fail "bad name rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","icc":"/tmp/a]==]b"}]}' 2>/dev/null; then fail "lua-breaking icc rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","evil":1}]}' 2>/dev/null; then fail "unknown key rejected"; fi
pass "validation rejects bad input"

# ---- disable + mirror + icc + global
# DP-2's kept intent still has cm:hdr from the tests above; move it to "auto"
# in the same change, since icc together with hdr is now rejected (6a).
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":false},{"name":"DP-2","cm":"auto","icc":"/home/p/My Profile.icc","vrr":1}],"global":{"cm_auto_hdr":0}}' >/dev/null
lua="$(cat "$sandbox/state/candela-layout.lua")"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", disabled = true })' "disabled display rule"
assert_contains "$lua" 'icc = [==[/home/p/My Profile.icc]==]' "icc path as long string"
assert_contains "$lua" 'vrr = 1' "vrr written"
assert_contains "$lua" 'hl.config({ render = { cm_auto_hdr = 0 } })' "global auto-hdr written"
pass "disable, icc, vrr, global"

# ---- hdr shortcut
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":true}]}' >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1)"
assert_contains "$out" "pending" "hdr on is a timed apply"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_max_luminance' "$sandbox/state/pending.json")" "203" "hdr on anchors SDR white at 203"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_min_luminance' "$sandbox/state/pending.json")" "0.2" "hdr on keeps Hyprland min when EDID says 0"
run_cli "$sandbox" revert >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1 --sdr-white 9000 --now)"
assert_eq "$(jq -r '.displays["DP-1"].sdr_max_luminance' "$sandbox/state/intent.json")" "497" "SDR white clamped to max-average luminance"
run_cli "$sandbox" hdr off --display DP-1 --now >/dev/null
assert_eq "$(jq -r '.displays["DP-1"].cm' "$sandbox/state/intent.json")" "srgb" "hdr off returns to srgb"
assert_eq "$(jq -r '.displays["DP-1"] | has("sdr_max_luminance")' "$sandbox/state/intent.json")" "false" "hdr off clears SDR white"
pass "hdr shortcut"

# ---- icc list
out="$(run_cli "$sandbox" icc list)"
jq -e 'type == "array"' <<<"$out" >/dev/null || fail "icc list is a JSON array"
pass "icc list"

# ---- apply writes a transaction token, and the timer names it
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
token="$(jq -r '.token' "$sandbox2/state/pending.json")"
[[ -n $token && $token != "null" ]] || fail "pending.json carries a token" "$token"
assert_contains "$(cat "$sandbox2/systemd-run.log")" "revert --expired --token $token" "timer command line names the token"
pass "apply writes a transaction token and arms the timer with it"

# ---- a failed apply keeps recovery when even the explicit baseline replay fails
sandbox2="$(new_sandbox)"
if FAKE_HYPRCTL_EVAL_FAIL=1 run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' 2>/dev/null; then
  fail "apply exits non-zero when hyprctl rejects the eval"
fi
[[ -s $sandbox2/state/pending.json ]] || fail "failed recovery retains pending journal"
assert_eq "$(jq -r .phase "$sandbox2/state/pending.json")" "failed" "failed apply records recovery phase"
assert_eq "$(jq -r .recovery.available "$sandbox2/state/pending.json")" "true" "failed apply advertises recovery"
assert_contains "$(cat "$sandbox2/systemctl.log")" "stop" "unwind stops the timer"
assert_contains "$(cat "$sandbox2/hyprctl.log")" "reload" "unwind reloads before replaying the observed baseline"
run_cli "$sandbox2" revert >/dev/null
[[ ! -e $sandbox2/state/pending.json ]] || fail "a later successful recovery clears the journal"
pass "a failed apply never discards an unverified recovery"

# ---- --now cannot confirm unrelated fields already waiting for Keep
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2,"cm":"hdr","bitdepth":10}]}' >/dev/null
out="$(run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","sdr_max_luminance":220}]}')"
assert_contains "$out" "pending" "--now joins an existing transaction"
[[ -s $sandbox2/state/pending.json ]] || fail "joined --now retains confirmation"
[[ ! -e $sandbox2/state/intent.json ]] || fail "joined --now does not persist pending fields"
assert_eq "$(jq -r '.intent.displays["DP-1"].scale' "$sandbox2/state/pending.json")" "2" "unrelated pending scale remains pending"
run_cli "$sandbox2" revert >/dev/null
pass "--now joins, and never silently keeps, an outstanding preview"

# ---- first use restores observed non-default state and exact prior files
sandbox2="$(new_sandbox)"
jq 'map(if .name=="DP-1" then .scale=1.37 | .sdrBrightness=1.23 else . end)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
: > "$sandbox2/state/candela-layout.lua"
printf 'shared flag bytes\n\n' > "$sandbox2/state/internal-monitor-disable.lua"
cp "$sandbox2/state/internal-monitor-disable.lua" "$sandbox2/flag-before"
: > "$sandbox2/state/internal-monitor-scale"
cp "$sandbox2/monitors.json" "$sandbox2/before.json"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2,"sdrbrightness":2}]}'>/dev/null
FAKE_HYPRCTL_PRESERVE_OMITTED=1 run_cli "$sandbox2" revert >/dev/null
assert_eq "$(jq -S 'map({name,scale,sdrBrightness})' "$sandbox2/monitors.json")" "$(jq -S 'map({name,scale,sdrBrightness})' "$sandbox2/before.json")" "revert replays first-use observed baseline"
[[ -f $sandbox2/state/candela-layout.lua && ! -s $sandbox2/state/candela-layout.lua ]] || fail "empty layout restored as empty"
cmp -s "$sandbox2/flag-before" "$sandbox2/state/internal-monitor-disable.lua" || fail "shared flag content restored byte-for-byte"
[[ -f $sandbox2/state/internal-monitor-scale && ! -s $sandbox2/state/internal-monitor-scale ]] || fail "empty internal scale restored as empty"
pass "first-use revert preserves observed state and byte-exact file presence"

# ---- a display unplugged during a preview does not make revert impossible
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
for f in monitors.json monitors.pristine.json; do
  jq 'map(select(.name != "DP-2"))' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"
done
run_cli "$sandbox2" revert >/dev/null || fail "revert succeeds when a baseline display has gone"
[[ ! -e $sandbox2/state/pending.json ]] || fail "journal cleared after a revert with a missing display"
pass "a display that vanished mid-preview is not required by revert"

# ---- revert --expired only acts when the token matches a still-pending change
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" revert --expired --token "not-the-real-token")"
assert_eq "$out" "nothing to revert" "mismatched token does nothing"
[[ -s $sandbox2/state/pending.json ]] || fail "mismatched token leaves pending.json in place"
[[ -z "$(cat "$sandbox2/hyprctl.log")" ]] || fail "mismatched token does not reload" "$(cat "$sandbox2/hyprctl.log")"

real_token="$(jq -r '.token' "$sandbox2/state/pending.json")"
out="$(run_cli "$sandbox2" revert --expired --token "$real_token")"
assert_eq "$out" "reverted" "matching token reverts"
[[ ! -e $sandbox2/state/pending.json ]] || fail "matching token clears pending.json"
assert_contains "$(cat "$sandbox2/hyprctl.log")" "reload" "matching token reloads"

: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" revert --expired --token "$real_token")"
assert_eq "$out" "nothing to revert" "no pending: expired revert does nothing"
[[ -z "$(cat "$sandbox2/hyprctl.log")" ]] || fail "no pending: expired revert does not reload" "$(cat "$sandbox2/hyprctl.log")"
pass "revert --expired only acts on a matching token"

# ---- top-level keys: only displays/global are accepted, and one must be present
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" apply '{"unexpected":true}' 2>/dev/null; then fail "unknown top-level key rejected"; fi
if run_cli "$sandbox2" apply '{}' 2>/dev/null; then fail "empty change rejected"; fi
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json armed by a rejected top-level change"
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":1.8}]}')"
assert_contains "$out" "pending" "a valid change still applies"
pass "top-level keys are validated"

# ---- colour invariants apply to the merged display (existing intent + change)
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","icc":"/tmp/a.icc","cm":"hdr"}]}' 2>/dev/null; then
  fail "icc together with cm hdr rejected"
fi
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","icc":"/tmp/a.icc","cm":"hdredid"}]}' 2>/dev/null; then
  fail "icc together with cm hdredid rejected"
fi
# supports_hdr follows Hyprland's own convention: -1 forces HDR off, 0 is
# auto/EDID (the default, must NOT block hdr), 1 forces it on.
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","supports_hdr":-1,"cm":"hdr"}]}' 2>/dev/null; then
  fail "supports_hdr forced off (-1) together with cm hdr rejected"
fi
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","supports_hdr":0,"cm":"hdr"}]}')"
assert_contains "$out" "pending" "supports_hdr 0 (auto/EDID default) does not block hdr"
run_cli "$sandbox2" revert >/dev/null
# kept intent already has cm:hdr; a later change that only sets icc must be
# checked against that merged state, not just the change in isolation.
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","icc":"/tmp/a.icc"}]}' 2>/dev/null; then
  fail "icc rejected against a kept cm:hdr intent (merged-state check)"
fi
pass "colour invariants apply to the merged display, not just the change"

# ---- apply --now reloads and checks configerrors, like keep
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
log="$(cat "$sandbox2/hyprctl.log")"
assert_contains "$log" "reload" "apply --now reloads"
assert_contains "$log" "configerrors" "apply --now checks configerrors"
pass "apply --now validates the written Lua like keep does"

# ---- structural check: every display key merge_intent accepts must reach
# generate_lua's output, or the timer's plain `hyprctl reload` cannot
# reconstruct it after a revert. "enabled" is the one exception: Hyprland's
# hl.monitor has no such key, so it is folded into the presence/absence of
# "disabled" instead of being written verbatim (see the loop's note below).
sandbox2="$(new_sandbox)"
change='{"displays":[{"name":"DP-2",
  "mode":"preferred","position":"100x50","scale":1.5,"transform":1,
  "vrr":1,"enabled":true,"mirror":"DP-1","bitdepth":10,"cm":"auto",
  "sdr_eotf":"srgb","sdrbrightness":1.2,"sdrsaturation":1.1,
  "sdr_min_luminance":0.2,"sdr_max_luminance":203,
  "min_luminance":0.05,"max_luminance":500,"max_avg_luminance":450,
  "icc":"/home/p/profile.icc","supports_hdr":1,"supports_wide_color":1
}]}'
run_cli "$sandbox2" apply --now "$change" >/dev/null
lua="$(cat "$sandbox2/state/candela-layout.lua")"
for key in mode position scale transform vrr mirror bitdepth cm sdr_eotf \
           sdrbrightness sdrsaturation sdr_min_luminance sdr_max_luminance \
           max_avg_luminance icc supports_hdr supports_wide_color; do
  assert_contains "$lua" "$key = " "generated Lua emits $key"
done
# min_luminance/max_luminance searched with a leading ", " so the match can't
# land inside sdr_min_luminance/sdr_max_luminance, which contain them as a substring.
assert_contains "$lua" ", min_luminance = " "generated Lua emits min_luminance distinctly from sdr_min_luminance"
assert_contains "$lua" ", max_luminance = " "generated Lua emits max_luminance distinctly from sdr_max_luminance"
pass "every accepted display key reaches the generated Lua (enabled excluded: see note above)"

# ---- the preview lives in a toggles file, loaded after the layout
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
[[ -s $sandbox2/state/candela-pending.lua ]] || fail "pending toggles file written on a timed apply"
assert_contains "$(cat "$sandbox2/state/candela-pending.lua")" 'output = "DP-2", disabled = false, mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 203' "pending file carries the change"
assert_contains "$(head -1 "$sandbox2/state/candela-pending.lua")" "Generated by" "pending file carries the header"
# A reload from anywhere else (a theme change, Omarchy's clamshell script)
# re-reads the toggles directory: the preview stays on the glass.
PATH="$sandbox2/bin:$PATH" hyprctl reload >/dev/null
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .colorManagementPreset')" "hdr" "a foreign reload keeps the preview"
run_cli "$sandbox2" revert >/dev/null
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "revert removes the pending toggles file"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .colorManagementPreset')" "srgb" "revert returns the display to the kept state"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
run_cli "$sandbox2" keep >/dev/null
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "keep removes the pending toggles file"
pass "the preview is a toggles file: a foreign reload keeps it, keep and revert remove it"

# ---- readback: a change the compositor did not land on is undone, not left pending
sandbox2="$(new_sandbox)"
if out="$(FAKE_HYPRCTL_IGNORE_SCALE=1 run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' 2>&1)"; then
  fail "apply exits non-zero when the readback disagrees"
fi
assert_contains "$out" "scale" "the mismatch names the field"
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json survives a failed readback"
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "no pending toggles file survives a failed readback"
grep -qx 'reload' "$sandbox2/hyprctl.log" || fail "a failed readback unwinds with a reload"
pass "a change the compositor did not land on is undone"

# ---- keep proves the layout file ran on reload
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","scale":2}]}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'omarchy_candela_layout_probe = "' "layout carries a load probe"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","scale":1.6}]}' >/dev/null
if out="$(FAKE_HYPRCTL_TOGGLES_NOT_LOADED=1 run_cli "$sandbox2" keep 2>&1)"; then
  fail "keep fails when the layout file did not run"
fi
assert_contains "$out" "did not run" "keep says the layout file did not run"
assert_contains "$out" "doctor" "keep points at doctor"
pass "keep proves the layout file ran"

# ---- a display switched off keeps its geometry and comes back where it was
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
assert_eq "$(jq -r '.displays["DP-2"].position' "$sandbox2/state/intent.json")" "2400x0" "position remembered at switch-off"
assert_eq "$(jq -r '.displays["DP-2"].scale' "$sandbox2/state/intent.json")" "1.6" "scale remembered at switch-off"
assert_eq "$(jq -r '.displays["DP-2"].mode' "$sandbox2/state/intent.json")" "3840x2560@59.98" "mode remembered at switch-off"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .disabled')" "true" "display is off"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":true}]}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "DP-2", disabled = false, mode = "3840x2560@59.98", position = "2400x0", scale = 1.6' "a re-enabled display returns to its old place, not 0x0"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .x')" "2400" "and the compositor agrees"
pass "switching a display off remembers its geometry"

# ---- the last enabled display cannot be switched off from the CLI either
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","enabled":false}]}' 2>/dev/null; then fail "switching off the last display rejected"; fi
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json armed by a rejected switch-off"
pass "the last enabled display stays on"

# ---- recover: every display off, the built-in panel (else the first) comes back
sandbox2="$(new_sandbox)"
jq 'map(.disabled = true | .width = 0 | .height = 0)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered DP-1" "recover names the display it switched on"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-1") | .disabled')" "false" "DP-1 is on after recover"
assert_eq "$(run_cli "$sandbox2" recover)" "nothing to recover" "recover is a no-op with a display on"
# A stale journal must not capture the rescue as a timed preview.
for f in monitors.json monitors.pristine.json; do jq 'map(.disabled = true)' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"; done
printf '%s\n' '{"token":"stale","phase":"failed","intent":{"version":1,"displays":{},"global":{}}}' > "$sandbox2/state/pending.json"
: > "$sandbox2/state/candela-pending.lua"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered DP-1" "recover with a stale journal still rescues"
[[ ! -e $sandbox2/state/pending.json ]] || fail "recover discards the stale journal instead of joining it"
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "recover discards the stale pending Lua"
assert_eq "$(jq -r '.displays["DP-1"].enabled' "$sandbox2/state/intent.json")" "true" "the rescue was kept, not previewed"
sandbox2="$(new_sandbox laptop)"
jq 'map(.disabled = true | .width = 0 | .height = 0)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered eDP-1" "recover prefers the built-in panel"
pass "recover"

# ---- the built-in panel is switched off through Omarchy's own toggle
sandbox2="$(new_sandbox laptop)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","enabled":false}]}' >/dev/null
flag="$sandbox2/state/internal-monitor-disable.lua"
[[ -f $flag ]] || fail "Omarchy's internal-monitor-disable flag written"
assert_eq "$(cat "$flag")" 'hl.monitor({ output = "eDP-1", disabled = true })' "flag has Omarchy's own content"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "eDP-1", disabled' "layout carries no disable rule of its own for the panel"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" "internal-monitor-disable" "layout says where the panel's off state lives"
assert_eq "$(jq -r '.displays["eDP-1"] | has("enabled")' "$sandbox2/state/intent.json")" "false" "intent does not store enabled for the panel"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "eDP-1") | .disabled')" "true" "panel is off"
# A timed re-enable removes the flag; reverting puts it back.
run_cli "$sandbox2" apply '{"displays":[{"name":"eDP-1","enabled":true}]}' >/dev/null
[[ ! -e $flag ]] || fail "a timed re-enable removes the flag"
assert_eq "$(jq -r '.files.internalFlag.present' "$sandbox2/state/pending.json")" "true" "pending snapshots the flag byte-for-byte"
run_cli "$sandbox2" revert >/dev/null
[[ -f $flag ]] || fail "revert restores the flag"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "eDP-1") | .disabled')" "true" "panel is off again after revert"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","enabled":true}]}' >/dev/null
[[ ! -e $flag ]] || fail "a kept re-enable removes the flag"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "eDP-1", disabled = false, mode = "2880x1800@60", position = "0x0", scale = 2' "the re-enabled panel has a full rule again"
pass "the built-in panel's off state is Omarchy's flag"

# ---- the panel's kept scale is where Omarchy's clamshell script looks for it
sandbox2="$(new_sandbox laptop)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","scale":1.5}]}' >/dev/null
assert_eq "$(cat "$sandbox2/state/internal-monitor-scale")" "1.5" "internal-monitor-scale written on keep"
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
[[ ! -e $sandbox2/state/internal-monitor-scale ]] || fail "no scale file without a built-in panel"
pass "internal-monitor-scale follows the kept scale"

# ---- state carries Hyprland's animations switch as the reduced-motion preference
sandbox2="$(new_sandbox)"
assert_eq "$(run_cli "$sandbox2" state | jq -r .animations)" "true" "animations on by default"
jq '.animations = false' "$sandbox2/global.json" > "$sandbox2/g.tmp" && mv "$sandbox2/g.tmp" "$sandbox2/global.json"
assert_eq "$(run_cli "$sandbox2" state | jq -r .animations)" "false" "animations off is reported"
pass "state reports whether Hyprland animates"

# ---- report is safe to paste into a public issue
sandbox2="$(new_sandbox)"
for f in monitors.json monitors.pristine.json; do
  jq 'map(.serial = "SN0123456789" | .description = (.description + " SN0123456789"))' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"
done
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","icc":"'"$sandbox2"'/profiles/panel.icc"}]}' >/dev/null 2>&1 || true
run_cli "$sandbox2" keep >/dev/null 2>&1 || true
out="$(run_cli "$sandbox2" report)"
assert_contains "$out" "## Candela report" "report has its heading"
assert_contains "$out" "| DP-1 | Huawei Technologies Co., Inc. MateView |" "report lists each display by make and model"
assert_contains "$out" "### doctor" "report includes doctor"
assert_not_contains "$out" "SN0123456789" "no serial number"
assert_not_contains "$out" "sha256:" "no EDID hash"
assert_not_contains "$out" "$sandbox2" "no home path"
assert_contains "$out" '"icc": "~/profiles/panel.icc"' "a kept path under home is shown from ~"
[[ -z $(ls "$sandbox2/state" | grep pending) ]] || fail "report changes nothing"
pass "report is readable and carries no serial, hash or home path"

# ---- doctor
sandbox2="$(new_sandbox)"
mkdir -p "$sandbox2/.config/hypr"
printf 'require("default.hypr.omarchy")\nrequire("hypr.monitors")\nrequire("default.hypr.toggles")\n' > "$sandbox2/.config/hypr/hyprland.lua"
printf 'local omarchy_monitor_scale = "auto"\nhl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })\n' > "$sandbox2/.config/hypr/monitors.lua"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","scale":2}]}' >/dev/null
out="$(run_cli "$sandbox2" doctor)" || fail "doctor exits 0 on a healthy sandbox" "$out"
assert_contains "$out" "ok    Hyprland ran" "doctor confirms the layout ran"
assert_contains "$out" "toggles directory" "doctor checks the toggles require"
assert_not_contains "$out" "FAIL" "doctor reports no failure"
sed -i '/default.hypr.toggles/d' "$sandbox2/.config/hypr/hyprland.lua"
if out="$(run_cli "$sandbox2" doctor)"; then fail "doctor exits 1 when the toggles are not required"; fi
assert_contains "$out" "FAIL  $sandbox2/.config/hypr/hyprland.lua does not require" "doctor names the missing require"
pass "doctor"

# ---- every display off: Hyprland's FALLBACK output is not a display
sandbox2="$(new_sandbox)"
for f in monitors.json; do
  jq 'map(.disabled = true | .width = 0 | .height = 0) + [{"name":"FALLBACK","description":"","make":"","model":"","serial":"","disabled":false,"focused":true,"width":1920,"height":1080,"refreshRate":60,"x":0,"y":0,"scale":1,"transform":0,"mirrorOf":"none","availableModes":[]}]' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"
done
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -r '[.displays[].name] | join(",")' <<<"$state")" "DP-1,DP-2" "FALLBACK is not listed as a display"
assert_eq "$(jq -r '[.displays[] | select(.enabled)] | length' <<<"$state")" "0" "with every real display off, none is enabled"
out="$(run_cli "$sandbox2" recover)"
assert_eq "$out" "recovered DP-1" "recover is not fooled by FALLBACK"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" "FALLBACK" "no rule is written for FALLBACK"
pass "Hyprland's FALLBACK output never counts as a display"

# ---- a display that is not connected keeps its last rule
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
dp2_rule="$(grep 'output = "DP-2"' "$sandbox2/state/candela-layout.lua")"
for f in monitors.json monitors.pristine.json; do
  jq 'map(select(.name != "DP-2"))' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"
done
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
lua="$(cat "$sandbox2/state/candela-layout.lua")"
assert_contains "$lua" "$dp2_rule" "the unplugged display's rule survives a keep, word for word"
assert_contains "$lua" "-- Not connected now." "and the file says why it is there"
assert_contains "$lua" 'output = "DP-1", disabled = false, mode = "3840x2560@59.98", position = "0x0", scale = 2' "the connected display gets the new rule"
assert_eq "$(grep -c 'output = "DP-2"' <<<"$lua")" "1" "the kept rule is written once"
out="$(run_cli "$sandbox2" doctor || true)"
assert_contains "$out" "kept rules wait for displays not connected now: DP-2" "doctor names it"
assert_not_contains "$(cat "$sandbox2/eval-last.txt")" 'output = "DP-2"' "nothing is sent live for a display that is not there"
pass "a display that is not connected keeps its rule"

# ---- workspace plan: a workspace-only change is kept at once and moves open workspaces home
split='{"workspaces":{"homes":{"1":"DP-1","2":"DP-1","3":"DP-1","4":"DP-1","5":"DP-1","6":"DP-2","7":"DP-2","8":"DP-2","9":"DP-2","10":"DP-2"}}}'
sandbox2="$(new_sandbox)"
: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" apply "$split")"
assert_eq "$out" "kept" "a workspace-only change needs no countdown"
[[ ! -e $sandbox2/state/pending.json ]] || fail "nothing is left pending"
lua="$(cat "$sandbox2/state/candela-layout.lua")"
assert_contains "$lua" 'hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true })' "first home on each display is shown on connect"
assert_contains "$lua" 'hl.workspace_rule({ workspace = "2", monitor = "DP-1" })' "workspace text is the string form Omarchy's layout toggle uses"
assert_contains "$lua" 'hl.workspace_rule({ workspace = "6", monitor = "DP-2", default = true })' "DP-2 shows 6 when it lights up"
assert_contains "$lua" 'hl.workspace_rule({ workspace = "10", monitor = "DP-2" })' "workspace 10 is planned"
assert_not_contains "$lua" "persistent" "no workspace is made persistent"
assert_eq "$(jq -r '.[] | select(.id == 2) | .monitor' "$sandbox2/workspaces.json")" "DP-1" "open workspace 2 was sent home to DP-1"
assert_eq "$(jq -r '.[] | select(.id == 1) | .monitor' "$sandbox2/workspaces.json")" "DP-1" "workspace 1 was already home"
assert_eq "$(grep -c 'workspace.move' "$sandbox2/hyprctl.log")" "1" "only the workspace that was away is moved"
assert_eq "$(jq -r '.[] | select(.workspaceString == "7") | .monitor' "$sandbox2/wsrules.json")" "DP-2" "the reload loaded the rules"
[[ -s $sandbox2/state/undo.json ]] || fail "the change can be undone"
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -r '.workspaces.kept.homes["6"]' <<<"$state")" "DP-2" "state carries the kept plan"
assert_eq "$(jq -r '.workspaces.open | length' <<<"$state")" "2" "state carries the open workspaces"
assert_eq "$(jq -r '.undo | type' <<<"$state")" "object" "state says an undo is available"
pass "a workspace plan is kept at once and sends open workspaces home"

# ---- revert undoes the plan and puts workspaces back
out="$(run_cli "$sandbox2" revert)"
assert_eq "$out" "reverted" "revert undoes the workspace change"
assert_eq "$(jq -r '.workspaces // "off"' "$sandbox2/state/intent.json")" "off" "the plan is off again"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" "workspace_rule" "no rules are left"
assert_eq "$(jq -r '.[] | select(.id == 2) | .monitor' "$sandbox2/workspaces.json")" "DP-2" "workspace 2 is back where it was"
[[ ! -e $sandbox2/state/undo.json ]] || fail "the undo is used once"
assert_eq "$(run_cli "$sandbox2" revert)" "reverted" "a second revert has nothing to undo"
assert_eq "$(jq -r '.workspaces // "off"' "$sandbox2/state/intent.json")" "off" "and changes nothing"
pass "revert undoes a workspace plan"

# ---- undo restores the previous plan exactly, not merged
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"1":"DP-1","2":"DP-2"}}}' >/dev/null
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"3":"DP-2"},"shows":{"DP-2":"3"}}}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'workspace = "3", monitor = "DP-2", default = true' "an explicit show wins over the lowest home"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'hl.workspace_rule({ workspace = "2", monitor = "DP-2" })' "2 is no longer DP-2's default"
run_cli "$sandbox2" revert >/dev/null
assert_eq "$(jq -c '.workspaces' "$sandbox2/state/intent.json")" '{"homes":{"1":"DP-1","2":"DP-2"}}' "the earlier plan is back as it was"
pass "undo replaces the plan with the one before"

# ---- a show follows its workspace: moving the home away drops it
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"6":"DP-2","7":"DP-2"},"shows":{"DP-2":"7"}}}' >/dev/null
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"7":"DP-1"}}}' >/dev/null
assert_eq "$(jq -c '.workspaces' "$sandbox2/state/intent.json")" '{"homes":{"6":"DP-2","7":"DP-1"}}' "DP-2 no longer shows a workspace that left it"
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"6":null,"7":null}}}' >/dev/null
assert_eq "$(jq -r '.workspaces // "off"' "$sandbox2/state/intent.json")" "off" "removing the last home turns the plan off"
pass "shows follow their workspaces; no homes is off"

# ---- validation of the plan
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" apply '{"workspaces":{"homes":{"11":"DP-1"}}}' 2>/dev/null; then fail "workspace 11 rejected"; fi
if run_cli "$sandbox2" apply '{"workspaces":{"homes":{"1":"FALLBACK"}}}' 2>/dev/null; then fail "FALLBACK rejected as a home"; fi
if run_cli "$sandbox2" apply '{"workspaces":{"homes":{"1":"DP-1;x"}}}' 2>/dev/null; then fail "bad display name rejected"; fi
if run_cli "$sandbox2" apply '{"workspaces":{"layouts":{}}}' 2>/dev/null; then fail "unknown workspaces key rejected"; fi
if run_cli "$sandbox2" apply '{"workspaces":{"shows":{"DP-1":"0"}}}' 2>/dev/null; then fail "show must name workspace 1 to 10"; fi
if run_cli "$sandbox2" apply '{"workspaces":[1]}' 2>/dev/null; then fail "workspaces must be an object"; fi
run_cli "$sandbox2" apply "$split" >/dev/null
if out="$(run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","mirror":"DP-1"}]}' 2>&1)"; then fail "a home cannot become a mirror"; fi
assert_contains "$out" "DP-2 mirrors DP-1, so it cannot be the home of workspace" "the refusal says why"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","mirror":"DP-1"}],"workspaces":{"homes":{"6":"DP-1","7":"DP-1","8":"DP-1","9":"DP-1","10":"DP-1"}}}' >/dev/null \
  || fail "mirroring works when the same change moves the homes"
pass "the plan is validated, and a mirror is never a home"

# ---- a change to displays and workspaces together gets the countdown, and revert moves workspaces back
sandbox2="$(new_sandbox)"
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}],"workspaces":{"homes":{"2":"DP-1"}}}')"
assert_contains "$out" "pending" "a change that touches a display keeps its countdown"
assert_eq "$(jq -r '.[] | select(.id == 2) | .monitor' "$sandbox2/workspaces.json")" "DP-1" "the preview moved workspace 2"
assert_contains "$(cat "$sandbox2/state/candela-pending.lua")" 'workspace = "2", monitor = "DP-1"' "the preview file carries the plan"
assert_eq "$(jq -r '.workspacesBefore | map(select(.id == 2))[0].monitor' "$sandbox2/state/pending.json")" "DP-2" "the journal records where it was"
run_cli "$sandbox2" revert >/dev/null
assert_eq "$(jq -r '.[] | select(.id == 2) | .monitor' "$sandbox2/workspaces.json")" "DP-2" "revert puts workspace 2 back"
assert_eq "$(jq length "$sandbox2/wsrules.json")" "0" "and the reload drops the preview's rules"
[[ ! -e $sandbox2/state/undo.json ]] || fail "a timed change leaves no undo"
pass "a mixed change is timed, and revert puts the workspaces back"

# ---- a move the compositor ignores undoes the change
sandbox2="$(new_sandbox)"
if out="$(FAKE_HYPRCTL_MOVE_IGNORED=1 run_cli "$sandbox2" apply "$split" 2>&1)"; then fail "an ignored move is not reported as kept"; fi
assert_contains "$out" "the workspaces did not move, so it was undone: workspace 2 is on DP-2, wanted DP-1" "the failure names the workspace"
assert_eq "$(jq -r '.workspaces // "off"' "$sandbox2/state/intent.json" 2>/dev/null || echo off)" "off" "nothing was kept"
[[ ! -e $sandbox2/state/pending.json ]] || fail "nothing is left pending"
pass "a workspace that does not move undoes the change"

# ---- workspaces home, and homes on a display that is not connected
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply "$split" >/dev/null
jq 'map(if .id == 2 then .monitor = "DP-2" else . end)' "$sandbox2/workspaces.json" > "$sandbox2/w.tmp" && mv "$sandbox2/w.tmp" "$sandbox2/workspaces.json"
assert_eq "$(run_cli "$sandbox2" workspaces home)" "home" "workspaces home runs"
assert_eq "$(jq -r '.[] | select(.id == 2) | .monitor' "$sandbox2/workspaces.json")" "DP-1" "a workspace moved by hand goes home"
for f in monitors.json monitors.pristine.json; do
  jq 'map(select(.name != "DP-2"))' "$sandbox2/$f" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/$f"
done
jq 'map(.monitor = "DP-1")' "$sandbox2/workspaces.json" > "$sandbox2/w.tmp" && mv "$sandbox2/w.tmp" "$sandbox2/workspaces.json"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'hl.workspace_rule({ workspace = "6", monitor = "DP-2", default = true })' "homes on an unplugged display stay in the file"
assert_eq "$(run_cli "$sandbox2" workspaces home)" "home" "nothing is sent to a display that is not there"
out="$(run_cli "$sandbox2" doctor || true)"
assert_contains "$out" "homes on DP-2, not connected now" "doctor says where those workspaces go"
assert_contains "$out" "Hyprland's rules match it" "doctor checks the live rules"
pass "workspaces home, and a plan that names an unplugged display"

# ---- turning the plan off removes the rules and moves nothing
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply "$split" >/dev/null
: > "$sandbox2/hyprctl.log"
assert_eq "$(run_cli "$sandbox2" apply '{"workspaces":null}')" "kept" "off is kept at once"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" "workspace_rule" "off writes no rules"
assert_not_contains "$(cat "$sandbox2/hyprctl.log")" "workspace.move" "off moves nothing"
pass "the plan turns off"

# ---- virtual displays: added apart, on a named workspace, kept at once
sandbox2="$(new_sandbox)"
: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" virtual add stage)"
assert_eq "$out" "VIRTUAL-1" "the first virtual display is VIRTUAL-1"
assert_contains "$(cat "$sandbox2/hyprctl.log")" "output create headless VIRTUAL-1" "Hyprland is asked for the output"
lua="$(cat "$sandbox2/state/candela-layout.lua")"
assert_contains "$lua" 'hl.monitor({ output = "VIRTUAL-1", disabled = false, mode = "1920x1080@60", position = "5120x0", scale = 1, transform = 0 })' "a stage sits apart, past the desk's right edge with a gap"
assert_contains "$lua" 'hl.workspace_rule({ workspace = "name:stage", monitor = "VIRTUAL-1", default = true })' "it opens on a named workspace of its own"
assert_eq "$(jq -r '.[] | select(.name == "VIRTUAL-1") | "\(.width)x\(.height)@\(.x),\(.y)"' "$sandbox2/monitors.json")" "1920x1080@5120,0" "the output landed where the rule says"
assert_eq "$(jq -r '.[] | select(.name == "stage") | .monitor' "$sandbox2/workspaces.json")" "VIRTUAL-1" "the named workspace is on it"
assert_eq "$(jq -c '.virtual["VIRTUAL-1"]' "$sandbox2/state/intent.json")" '{"label":"Stage","use":"stage"}' "intent records what it is for"
[[ ! -e $sandbox2/state/pending.json ]] || fail "no countdown for a virtual display"
[[ -s $sandbox2/state/undo.json ]] || fail "adding it can be undone"
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -r '.displays[] | select(.name == "VIRTUAL-1") | .virtual' <<<"$state")" "true" "state marks it virtual"
assert_eq "$(jq -r '.virtual.displays["VIRTUAL-1"].workspace' <<<"$state")" "stage" "state names its workspace"
assert_eq "$(jq -c '[.virtual.addresses[].address]' <<<"$state")" '["192.168.1.89"]' "only LAN addresses are offered, not loopback or the VM bridge"
pass "a virtual display is added apart, on its own workspace, without a countdown"

# ---- a reload keeps it, and restore makes nothing twice
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
assert_eq "$(jq -r '[.[] | select(.name == "VIRTUAL-1")] | length' "$sandbox2/monitors.json")" "1" "a keep and its reload leave it in place"
assert_eq "$(run_cli "$sandbox2" virtual restore)" "restored 0" "restore makes nothing that exists"
jq 'map(select(.name != "VIRTUAL-1"))' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
echo '[]' > "$sandbox2/virtual.json"
assert_eq "$(run_cli "$sandbox2" virtual restore)" "restored 1" "restore recreates it after a restart"
assert_eq "$(jq -r '.[] | select(.name == "VIRTUAL-1") | .x' "$sandbox2/monitors.json")" "5120" "where it was"
pass "a virtual display survives reloads and is recreated at start"

# ---- viewing: the shell's own window; the network behind a password
: > "$sandbox2/systemd-run.log"
assert_eq "$(run_cli "$sandbox2" virtual view VIRTUAL-1 window on)" "VIRTUAL-1 window on" "window view starts"
assert_contains "$(cat "$sandbox2/omarchy-shell.log")" "io.github.pushmotta.candela preview VIRTUAL-1 on" "the shell draws the window view"
assert_not_contains "$(cat "$sandbox2/systemd-run.log")" "wayvnc" "and no VNC server is started for it"
if run_cli "$sandbox2" virtual view VIRTUAL-1 network on --address 0.0.0.0 2>/dev/null; then fail "every interface at once is refused"; fi
if run_cli "$sandbox2" virtual view VIRTUAL-1 network on --address 192.168.122.1 2>/dev/null; then fail "the VM bridge is not a LAN address"; fi
assert_eq "$(run_cli "$sandbox2" virtual view VIRTUAL-1 network on)" "VIRTUAL-1 network on" "network view starts"
conf="$(cat "$sandbox2/state/virtual/VIRTUAL-1/network.conf")"
assert_contains "$conf" "enable_auth=true" "network needs a password"
assert_contains "$conf" "address=192.168.1.89" "on the one LAN address"
assert_contains "$conf" "port=5901" "VIRTUAL-1 listens on 5901"
assert_contains "$conf" "rsa_private_key_file=$sandbox2/state/virtual/VIRTUAL-1/rsa_key.pem" "with a kept RSA key"
assert_not_contains "$conf" "relax_encryption" "never relaxed encryption"
assert_eq "$(stat -c %a "$sandbox2/state/virtual/VIRTUAL-1/network.conf")" "600" "the config holding the password is private"
assert_contains "$(cat "$sandbox2/systemd-run.log")" "-o VIRTUAL-1 -S $sandbox2/runtime/omarchy-candela/VIRTUAL-1-network.ctl -R -d" "a display placed apart is watch-only, so the cursor cannot be left out of reach"
assert_eq "$(stat -c %a "$sandbox2/runtime/omarchy-candela")" "700" "the control socket's directory is the user's alone"
secret="$(run_cli "$sandbox2" virtual secret VIRTUAL-1)"
assert_eq "$(jq -r .username <<<"$secret")" "candela" "secret gives the username"
[[ $(jq -r .password <<<"$secret") =~ ^[a-hjkmnp-z2-9]{4}(-[a-hjkmnp-z2-9]{4}){3}$ ]] || fail "a password typed without shift: four groups of four, no look-alikes" "$secret"
pw1="$(jq -r .password <<<"$secret")"
assert_eq "$(jq -r 'has("qr")' <<<"$secret")" "false" "no QR code unless asked"
assert_eq "$(run_cli "$sandbox2" virtual secret VIRTUAL-1 --qr | jq -r .qr)" "$(printf PNGDATA | base64 -w0)" "--qr adds the password as a QR code"
assert_eq "$(run_cli "$sandbox2" state | jq -r '[.. | strings | select(. == "'"$pw1"'")] | length')" "0" "the password is never part of the state"
run_cli "$sandbox2" virtual view VIRTUAL-1 network off >/dev/null
run_cli "$sandbox2" virtual view VIRTUAL-1 network on >/dev/null
assert_eq "$(run_cli "$sandbox2" virtual secret VIRTUAL-1 | jq -r .password)" "$pw1" "the password is kept between starts"
: > "$sandbox2/systemd-run.log"
run_cli "$sandbox2" virtual view VIRTUAL-1 network on >/dev/null
assert_not_contains "$(cat "$sandbox2/systemd-run.log")" "wayvnc" "asking again with nothing changed does not restart it, so no one is dropped"
pw2="$(run_cli "$sandbox2" virtual secret VIRTUAL-1 --new | jq -r .password)"
[[ $pw2 != "$pw1" ]] || fail "--new replaces the password"
assert_contains "$(cat "$sandbox2/systemd-run.log")" "wayvnc" "and starts the server again so it takes effect"
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -c '.virtual.displays["VIRTUAL-1"].network | [.on, .address, .port, .atLogin, .input]' <<<"$state")" '[true,"192.168.1.89",5901,false,false]' "state reports network viewing, watch-only"
assert_eq "$(jq -r '.virtual.displays["VIRTUAL-1"].network.clients[0].address' <<<"$state")" "192.168.1.40" "and who is connected"
out="$(run_cli "$sandbox2" doctor || true)"
assert_contains "$out" "VIRTUAL-1 is offered on 192.168.1.89:5901 with a password and RSA-AES, watch-only" "doctor says what is on the network"
: > "$sandbox2/systemd-run.log"
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","position":"4800x0"}]}' >/dev/null
assert_contains "$(cat "$sandbox2/systemd-run.log")" "-o VIRTUAL-1 -S $sandbox2/runtime/omarchy-candela/VIRTUAL-1-network.ctl -R" "moving it beside starts its server again"
assert_not_contains "$(cat "$sandbox2/systemd-run.log")" " -d" "and beside, viewers may take input"
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","position":"5120x0"}]}' >/dev/null
pass "a virtual display is seen on a private socket, or on one LAN address behind a password"

# ---- removing it stops its servers before the output goes, and can be undone
: > "$sandbox2/wayvncctl.log"; : > "$sandbox2/hyprctl.log"
assert_eq "$(run_cli "$sandbox2" virtual remove VIRTUAL-1)" "removed VIRTUAL-1" "remove reports"
assert_contains "$(cat "$sandbox2/systemctl.log")" "stop omarchy-candela-network-VIRTUAL-1.service" "the network server is stopped"
assert_contains "$(cat "$sandbox2/omarchy-shell.log")" "preview VIRTUAL-1 off" "its window is closed"
assert_contains "$(cat "$sandbox2/hyprctl.log")" "output remove VIRTUAL-1" "then the output is removed"
assert_eq "$(jq -r 'has("virtual")' "$sandbox2/state/intent.json")" "false" "it is gone from intent, with no empty block left"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" "VIRTUAL-1" "and from the layout"
[[ ! -e $sandbox2/state/virtual/VIRTUAL-1 ]] || fail "its key and password are deleted"
assert_eq "$(run_cli "$sandbox2" revert)" "reverted" "revert undoes the removal"
assert_eq "$(jq -r '.[] | select(.name == "VIRTUAL-1") | .x' "$sandbox2/monitors.json")" "5120" "it comes back where it was"
assert_eq "$(run_cli "$sandbox2" revert)" "reverted" "a second revert has nothing to undo"
pass "removing a virtual display stops its servers first, and revert brings it back"

# ---- the parking guard, and real displays only for recover
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra --label "iPad Pro" >/dev/null
lua="$(cat "$sandbox2/state/candela-layout.lua")"
assert_contains "$lua" 'output = "VIRTUAL-1", disabled = false, mode = "2732x2048@60", position = "4800x0", scale = 2' "an extra screen sits flush beside the rightmost display"
assert_contains "$lua" 'workspace = "name:ipad-pro"' "the label becomes its workspace's name"
jq '. + [{"id":7,"name":"7","monitor":"VIRTUAL-1","windows":2}]' "$sandbox2/workspaces.json" > "$sandbox2/w.tmp" && mv "$sandbox2/w.tmp" "$sandbox2/workspaces.json"
assert_eq "$(run_cli "$sandbox2" virtual guard)" "moved 1" "a parked workspace is moved"
assert_eq "$(jq -r '.[] | select(.id == 7) | .monitor' "$sandbox2/workspaces.json")" "DP-1" "to the leftmost real display"
assert_eq "$(jq -r '.[] | select(.name == "ipad-pro") | .monitor' "$sandbox2/workspaces.json")" "VIRTUAL-1" "its own workspace stays"
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"9":"VIRTUAL-1"}}}' >/dev/null
jq '. + [{"id":9,"name":"9","monitor":"VIRTUAL-1","windows":1}]' "$sandbox2/workspaces.json" > "$sandbox2/w.tmp" && mv "$sandbox2/w.tmp" "$sandbox2/workspaces.json"
assert_eq "$(run_cli "$sandbox2" virtual guard)" "moved 0" "a workspace that lives there by plan stays"
jq 'map(if .name == "DP-1" or .name == "DP-2" then .disabled = true | .width = 0 else . end)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered DP-1" "a virtual display that is on does not stop recover"
pass "the parking guard, and recover counts real displays only"

# ---- validation and refusals
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" virtual add wall 2>/dev/null; then fail "an unknown use is refused"; fi
if run_cli "$sandbox2" virtual add stage --size 99999x10 2>/dev/null; then fail "an impossible size is refused"; fi
if run_cli "$sandbox2" virtual add stage --label 'a"b' 2>/dev/null; then fail "a label that could break Lua is refused"; fi
if run_cli "$sandbox2" virtual remove DP-1 2>/dev/null; then fail "a real display is never removed"; fi
run_cli "$sandbox2" virtual add stage >/dev/null
assert_eq "$(run_cli "$sandbox2" virtual add bench)" "VIRTUAL-2" "the next one is VIRTUAL-2"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "VIRTUAL-2", disabled = false, mode = "1366x768@60", position = "2400x1600"' "a test bench goes beside, below DP-2, since VIRTUAL-1 sits right of it"
assert_eq "$(run_cli "$sandbox2" virtual add stage)" "VIRTUAL-3" "a third, apart"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "VIRTUAL-3", disabled = false, mode = "1920x1080@60", position = "7360x0"' "past everything, VIRTUAL-1 included"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
if run_cli "$sandbox2" virtual add stage 2>/dev/null; then fail "nothing is added while a change waits for Keep"; fi
run_cli "$sandbox2" revert >/dev/null
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-2","mode":"1920x1080@60"}]}')"
assert_eq "$out" "kept" "resizing a virtual display needs no countdown"
if out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-2","cm":"hdr","bitdepth":10}]}' 2>&1)"; then fail "HDR on a virtual display is refused"; fi
assert_contains "$out" "VIRTUAL-2 is a virtual display: it is SDR, since nothing that shows it carries HDR or wide colour" "and the refusal says why"
for field in '"bitdepth":10' '"cm":"wide"' '"supports_hdr":1' '"icc":"/x.icc"' '"vrr":1' '"mirror":"DP-1"' '"sdr_max_luminance":203'; do
  if run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-2",'"$field"'}]}' 2>/dev/null; then fail "a virtual display refuses $field"; fi
done
pass "virtual displays are validated, and a real display is never removed"

# ---- install: Omarchy's installer, in a terminal, only when missing
sandbox2="$(new_sandbox)"
assert_eq "$(run_cli "$sandbox2" virtual install)" "wayvnc is installed" "nothing to do when wayvnc is there"
out="$(OMARCHY_CANDELA_WAYVNC=wayvnc-not-installed run_cli "$sandbox2" virtual install)"
assert_eq "$out" "installing wayvnc in a terminal" "a terminal is opened"
sleep 0.3
assert_eq "$(cat "$sandbox2/terminal.log")" "omarchy pkg add wayvnc" "running Omarchy's own installer"
pass "wayvnc is installed through Omarchy's installer, when asked"

# ---- the undo lasts two minutes and says what it undoes
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add stage >/dev/null
assert_eq "$(run_cli "$sandbox2" state | jq -r '.undo.what')" "adding VIRTUAL-1" "state says what an undo would undo"
jq '.since -= 121' "$sandbox2/state/undo.json" > "$sandbox2/u.tmp" && mv "$sandbox2/u.tmp" "$sandbox2/state/undo.json"
assert_eq "$(run_cli "$sandbox2" state | jq -r '.undo')" "null" "after two minutes there is no undo"
run_cli "$sandbox2" revert >/dev/null
assert_eq "$(jq -r '.virtual | has("VIRTUAL-1")' "$sandbox2/state/intent.json")" "true" "and a late revert removes nothing"
[[ ! -e $sandbox2/state/undo.json ]] || fail "the stale record is deleted"
run_cli "$sandbox2" apply '{"workspaces":{"homes":{"1":"DP-1"}}}' >/dev/null
assert_eq "$(run_cli "$sandbox2" state | jq -r '.undo.what')" "the workspace plan" "a plan change says so"
pass "an undo lasts two minutes and says what it undoes"

# ---- the firewall: a port it drops is reported, with the rule that would let the LAN in
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra >/dev/null
run_cli "$sandbox2" virtual view VIRTUAL-1 network on >/dev/null
assert_eq "$(run_cli "$sandbox2" state | jq -r '.virtual.displays["VIRTUAL-1"].network.firewall')" "open" "5901 is allowed from the LAN"
run_cli "$sandbox2" virtual view VIRTUAL-1 network on --port 5911 >/dev/null
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -r '.virtual.displays["VIRTUAL-1"].network.firewall' <<<"$state")" "blocked" "5911 is dropped"
assert_eq "$(jq -r '.virtual.displays["VIRTUAL-1"].network.firewallAllow' <<<"$state")" "ufw allow from 192.168.1.0/24 to any port 5911 proto tcp" "and the rule that lets only the LAN in"
assert_contains "$(run_cli "$sandbox2" doctor || true)" "the firewall (ufw) drops connections to port 5911" "doctor says so"
rm -f "$sandbox2/system-units/ufw.service"
assert_eq "$(run_cli "$sandbox2" state | jq -r '.virtual.displays["VIRTUAL-1"].network.firewall')" "open" "with ufw off, nothing is in the way"
pass "a firewall that drops the port is reported, with the rule to allow the LAN"


# ---- switching a virtual display off stops its network server first: wayvnc
# would otherwise move on to a real display and keep serving it
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra >/dev/null
run_cli "$sandbox2" virtual view VIRTUAL-1 network on >/dev/null
: > "$sandbox2/systemctl.log"
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","enabled":false}]}' >/dev/null
assert_contains "$(cat "$sandbox2/systemctl.log")" "stop omarchy-candela-network-VIRTUAL-1.service" "switching it off stops the server"
if run_cli "$sandbox2" virtual view VIRTUAL-1 network on 2>/dev/null; then fail "a display that is off is not served"; fi
assert_contains "$(run_cli "$sandbox2" virtual view VIRTUAL-1 network on 2>&1 || true)" "VIRTUAL-1 is off" "and says why"
pass "a virtual display that is switched off is never served"

# ---- a display switched off comes back on: Hyprland's hl.monitor keeps the
# fields a rule leaves out, so `disabled = true` sticks unless the rule that
# switches it on says otherwise
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra >/dev/null
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","enabled":false}]}' >/dev/null
assert_eq "$(jq -r '.[] | select(.name == "VIRTUAL-1") | .disabled' "$sandbox2/monitors.json")" "true" "the virtual display is off"
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","enabled":true}]}' >/dev/null || fail "switching it on is refused"
assert_eq "$(jq -r '.[] | select(.name == "VIRTUAL-1") | .disabled' "$sandbox2/monitors.json")" "false" "and it is on again"
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","enabled":true}]}' >/dev/null || fail "switching a real display on is refused"
assert_eq "$(jq -r '.[] | select(.name == "DP-2") | .disabled' "$sandbox2/monitors.json")" "false" "a real display comes back on too, in its preview"
pass "a display switched off comes back on"
# ---- Hyprland's hl.monitor keeps the fields a rule leaves out (the fake
# merges rules the same way), so a display switched off, or set to mirror,
# stays so in a live change unless the rule says otherwise. Every path that
# brings one back without a reload first:
mon() { jq -r --arg n "$2" ".[] | select(.name == \$n) | .$3" "$1/monitors.json"; }

sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "true" "DP-2 is kept off"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","enabled":true}]}' >/dev/null || fail "switching it on is refused"
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "false" "it is on in the preview"
run_cli "$sandbox2" keep >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "false" "and stays on once kept"
pass "a display kept off comes back on, in a preview and once kept"

sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":true}]}' >/dev/null || fail "switching it on at once is refused"
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "false" "on at once"
pass "a display kept off comes back on at once"

sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "true" "off in the preview"
run_cli "$sandbox2" revert >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 disabled)" "false" "and on again after revert"
pass "reverting a preview that switched a display off brings it back"

# recover: DP-2 kept off, then DP-1 switched off by something other than
# Candela, so every display is dark and the rescue has a rule to undo.
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
FAKE_DIR="$sandbox2" bash "$ROOT/test/fake-hyprctl.sh" eval 'hl.monitor({ output = "DP-1", disabled = true })' >/dev/null
assert_eq "$(mon "$sandbox2" DP-1 disabled)" "true" "every display is off"
assert_eq "$(run_cli "$sandbox2" recover 2>&1 | tail -1)" "recovered DP-1" "recover answers"
assert_eq "$(mon "$sandbox2" DP-1 disabled)" "false" "and DP-1 is on again"
pass "recover switches a display back on when every one is off"

sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","mirror":"DP-1"}]}' >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 mirrorOf)" "0" "DP-2 is kept mirroring DP-1, which Hyprland reports by its id"
assert_eq "$(run_cli "$sandbox2" state | jq -r '.displays[] | select(.name == "DP-2") | .mirrorOf')" "DP-1" "and the state names it"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","mirror":""}]}' >/dev/null || fail "ending the mirror is refused"
assert_eq "$(mon "$sandbox2" DP-2 mirrorOf)" "none" "the mirror ends in the preview"
assert_contains "$(cat "$sandbox2/eval-last.txt")" 'output = "DP-2", disabled = false, mode' "the rule says the display is on"
assert_contains "$(cat "$sandbox2/eval-last.txt")" 'mirror = ""' "and that it mirrors nothing"
run_cli "$sandbox2" keep >/dev/null
assert_eq "$(mon "$sandbox2" DP-2 mirrorOf)" "none" "and once kept"
pass "a kept mirror can be ended"

# A rule the user's own config gives a display Candela has no say on is
# left alone: no "on", no "no mirror" for it.
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","scale":2}]}' >/dev/null
assert_not_contains "$(grep '"DP-1"' "$sandbox2/state/candela-layout.lua")" "mirror" "no mirror field for a display intent says nothing about"
pass "displays intent says nothing about get no mirror field"

# ---- a virtual display's name and device: kept at once, the open workspace
# renamed with it, and both undone together
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra >/dev/null
assert_eq "$(jq -r '.[] | select(.monitor == "VIRTUAL-1") | .name' "$sandbox2/workspaces.json")" "tablet" "it opens on its workspace, named after its label"
run_cli "$sandbox2" apply '{"displays":[{"name":"VIRTUAL-1","mode":"2560x1600@60"}],"virtual":{"VIRTUAL-1":{"label":"  Pixel ","device":"pixel-tablet"}}}' >/dev/null
assert_eq "$(jq -c '.virtual["VIRTUAL-1"] | {label, device}' "$sandbox2/state/intent.json")" '{"label":"Pixel","device":"pixel-tablet"}' "the name (trimmed) and the device are kept"
[[ ! -s $sandbox2/state/pending.json ]] || fail "kept at once, with no countdown"
assert_eq "$(jq -r '.[] | select(.monitor == "VIRTUAL-1") | .name' "$sandbox2/workspaces.json")" "pixel" "the open workspace is renamed"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'workspace = "name:pixel", monitor = "VIRTUAL-1"' "and the rule names it"
state="$(run_cli "$sandbox2" state)"
assert_eq "$(jq -r '.virtual.displays["VIRTUAL-1"] | "\(.device) \(.workspace)"' <<<"$state")" "pixel-tablet pixel" "state carries both"
run_cli "$sandbox2" revert >/dev/null
assert_eq "$(jq -c '.virtual["VIRTUAL-1"] | {label, device}' "$sandbox2/state/intent.json")" '{"label":"Tablet","device":null}' "undo puts the name back and forgets the device"
assert_eq "$(jq -r '.[] | select(.monitor == "VIRTUAL-1") | .name' "$sandbox2/workspaces.json")" "tablet" "and the workspace's name"
run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"device":"pixel-tablet"}}}' >/dev/null
run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"device":null}}}' >/dev/null
assert_eq "$(jq -r '.virtual["VIRTUAL-1"] | has("device")' "$sandbox2/state/intent.json")" "false" "null forgets the device"
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"label":"   "}}}' 2>/dev/null; then fail "an empty name is refused"; fi
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"label":"two\nlines"}}}' 2>/dev/null; then fail "a name on two lines is refused"; fi
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"label":"a name far longer than thirty-two characters"}}}' 2>/dev/null; then fail "a long name is refused"; fi
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-2":{"label":"x"}}}' 2>/dev/null; then fail "a display that does not exist is refused"; fi
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"colour":"x"}}}' 2>/dev/null; then fail "an unknown field is refused"; fi
if run_cli "$sandbox2" apply '{"virtual":{"VIRTUAL-1":{"device":"Bad Device"}}}' 2>/dev/null; then fail "a malformed device is refused"; fi
pass "a virtual display can be renamed and remembers its device"

# ---- windows nobody can see: counted, and brought back
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" virtual add extra >/dev/null
vid="$(jq -r '.[] | select(.name == "VIRTUAL-1") | .id' "$sandbox2/monitors.json")"
jq -n --argjson v "$vid" '[{address:"0xa1", monitor:$v, workspace:{name:"tablet"}}, {address:"0xa2", monitor:$v, workspace:{name:"tablet"}}, {address:"0xb1", monitor:0, workspace:{name:"1"}}]' > "$sandbox2/clients.json"
assert_eq "$(run_cli "$sandbox2" state | jq -r '.virtual.displays["VIRTUAL-1"].windows')" "2" "two windows are on it"
jq 'map(if .name == "DP-1" then .focused = true | .activeWorkspace = {id: 1, name: "1"} else .focused = false end)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" virtual gather VIRTUAL-1)" "moved 2 to DP-1" "gather brings them to the focused display"
assert_eq "$(jq -c '[.[] | select(.monitor == 0) | .address] | sort' "$sandbox2/clients.json")" '["0xa1","0xa2","0xb1"]' "onto its workspace"
assert_contains "$(cat "$sandbox2/hyprctl.log")" 'hl.dsp.window.move({ workspace = "1", follow = false, window = "address:0xa1" })' "silently, by address"
assert_eq "$(run_cli "$sandbox2" state | jq -r '.virtual.displays["VIRTUAL-1"].windows')" "0" "and none are left there"
pass "windows on a virtual display are counted and can be brought back"

