#!/bin/bash

set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

sandbox="$(make_sandbox)"
trap 'rm -rf "$sandbox"' EXIT

# ---- state
state="$(run_cli "$sandbox" state)"
jq -e . <<<"$state" >/dev/null || fail "state is valid JSON" "$state"
assert_eq "$(jq -r '.displays | length' <<<"$state")" "2" "state lists both displays"
assert_eq "$(jq -r .focused <<<"$state")" "DP-1" "focused display reported"
assert_eq "$(jq -r '.displays[0].live.bitdepth' <<<"$state")" "8" "bitdepth derived from format"
assert_eq "$(jq -r '.displays[0].capabilities.supportsHdr' <<<"$state")" "true" "capabilities attached"
assert_eq "$(jq -r '.displays[0].brightness' <<<"$state")" "62" "brightness attached to focused display"
assert_eq "$(jq -r '.displays[1].brightness' <<<"$state")" "null" "brightness only read for focused display"
assert_eq "$(jq -r .pending <<<"$state")" "null" "nothing pending initially"
assert_eq "$(jq -r .global.cm_auto_hdr <<<"$state")" "1" "global auto-hdr read"
pass "state"

# ---- apply with timer
out="$(run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}')"
assert_contains "$out" "pending" "apply reports pending"
[[ -s $sandbox/state/pending.json ]] || fail "pending file written"
eval_chunk="$(cat "$sandbox/eval-last.txt")"
assert_contains "$eval_chunk" 'output = "DP-1", mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0' "untouched display declared explicitly"
assert_contains "$eval_chunk" 'output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 203' "changed display carries colour fields"
assert_contains "$(cat "$sandbox/systemd-run.log")" "revert --expired" "revert timer armed"
[[ ! -e $sandbox/state/displays-layout.lua ]] || fail "layout not persisted before keep"
pass "apply arms the timer and declares every display"

# ---- state while pending
state="$(run_cli "$sandbox" state)"
assert_eq "$(jq -r '.pending | type' <<<"$state")" "object" "state exposes pending"
assert_eq "$(jq -r '.displays[1].pendingConfig.cm' <<<"$state")" "hdr" "pending config attached per display"
pass "pending state"

# ---- chained apply keeps earlier pending fields
run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","sdr_max_luminance":250}]}' >/dev/null
eval_chunk="$(cat "$sandbox/eval-last.txt")"
assert_contains "$eval_chunk" 'cm = "hdr", sdr_max_luminance = 250' "chained apply merges onto pending"
pass "chained apply"

# ---- keep
out="$(run_cli "$sandbox" keep)"
assert_eq "$out" "kept" "keep reports kept"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after keep"
lua="$(cat "$sandbox/state/displays-layout.lua")"
assert_contains "$lua" "Generated by pmotta.displays" "layout header"
assert_contains "$lua" 'hl.monitor({ output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 250 })' "layout carries kept fields"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0 })' "layout declares the other display"
assert_eq "$(jq -r '.displays["DP-2"].cm' "$sandbox/state/intent.json")" "hdr" "intent persisted"
assert_contains "$(tail -3 "$sandbox/hyprctl.log")" "reload" "keep reloads"
pass "keep persists intent and layout"

# ---- revert drops pending and reloads
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
out="$(run_cli "$sandbox" revert)"
assert_eq "$out" "reverted" "revert reports"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after revert"
assert_eq "$(jq -r '.displays["DP-1"].scale // "none"' "$sandbox/state/intent.json")" "none" "reverted change not in intent"
pass "revert"

# ---- apply --now persists immediately
out="$(run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-2","sdr_max_luminance":203}]}')"
assert_eq "$out" "kept" "apply --now keeps"
assert_eq "$(jq -r '.displays["DP-2"].sdr_max_luminance' "$sandbox/state/intent.json")" "203" "apply --now persisted"
pass "apply --now"

# ---- validation
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","cm":"bogus"}]}' 2>/dev/null; then fail "bad cm rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2;x","bitdepth":10}]}' 2>/dev/null; then fail "bad name rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","icc":"/tmp/a]==]b"}]}' 2>/dev/null; then fail "lua-breaking icc rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","evil":1}]}' 2>/dev/null; then fail "unknown key rejected"; fi
pass "validation rejects bad input"

# ---- disable + mirror + icc + global
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":false},{"name":"DP-2","icc":"/home/p/My Profile.icc","vrr":1}],"global":{"cm_auto_hdr":0}}' >/dev/null
lua="$(cat "$sandbox/state/displays-layout.lua")"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", disabled = true })' "disabled display rule"
assert_contains "$lua" 'icc = [==[/home/p/My Profile.icc]==]' "icc path as long string"
assert_contains "$lua" 'vrr = 1' "vrr written"
assert_contains "$lua" 'hl.config({ render = { cm_auto_hdr = 0 } })' "global auto-hdr written"
pass "disable, icc, vrr, global"

# ---- hdr shortcut
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":true}]}' >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1)"
assert_contains "$out" "pending" "hdr on is a timed apply"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_max_luminance' "$sandbox/state/pending.json")" "203" "hdr on anchors SDR white at 203"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_min_luminance' "$sandbox/state/pending.json")" "0.2" "hdr on keeps Hyprland min when EDID says 0"
run_cli "$sandbox" revert >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1 --sdr-white 9000 --now)"
assert_eq "$(jq -r '.displays["DP-1"].sdr_max_luminance' "$sandbox/state/intent.json")" "497" "SDR white clamped to max-average luminance"
run_cli "$sandbox" hdr off --display DP-1 --now >/dev/null
assert_eq "$(jq -r '.displays["DP-1"].cm' "$sandbox/state/intent.json")" "srgb" "hdr off returns to srgb"
assert_eq "$(jq -r '.displays["DP-1"] | has("sdr_max_luminance")' "$sandbox/state/intent.json")" "false" "hdr off clears SDR white"
pass "hdr shortcut"

# ---- icc list
out="$(run_cli "$sandbox" icc list)"
jq -e 'type == "array"' <<<"$out" >/dev/null || fail "icc list is a JSON array"
pass "icc list"
