#!/bin/bash

set -euo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

sandbox="$(make_sandbox)"
sandboxes=("$sandbox")
trap 'rm -rf "${sandboxes[@]}"' EXIT

# A few of the newer tests below need a clean, isolated pending/timer state
# rather than the one this file keeps building up above; give them their own.
new_sandbox() {
  local dir
  dir="$(make_sandbox "$@")"
  sandboxes+=("$dir")
  echo "$dir"
}

# ---- state
state="$(run_cli "$sandbox" state)"
jq -e . <<<"$state" >/dev/null || fail "state is valid JSON" "$state"
assert_eq "$(jq -r '.displays | length' <<<"$state")" "2" "state lists both displays"
assert_eq "$(jq -r .focused <<<"$state")" "DP-1" "focused display reported"
assert_eq "$(jq -r '.displays[0].live.bitdepth' <<<"$state")" "8" "bitdepth derived from format"
assert_eq "$(jq -r '.displays[0].capabilities.supportsHdr' <<<"$state")" "true" "capabilities attached"
assert_eq "$(jq -r '.displays[0].brightness' <<<"$state")" "62" "brightness attached to focused display"
assert_eq "$(jq -r '.displays[1].brightness' <<<"$state")" "null" "brightness only read for focused display"
assert_eq "$(jq -r .pending <<<"$state")" "null" "nothing pending initially"
assert_eq "$(jq -r .global.cm_auto_hdr <<<"$state")" "1" "global auto-hdr read"
pass "state"

# ---- apply with timer
out="$(run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}')"
assert_contains "$out" "pending" "apply reports pending"
[[ -s $sandbox/state/pending.json ]] || fail "pending file written"
eval_chunk="$(cat "$sandbox/eval-last.txt")"
[[ $(head -1 "$sandbox/eval-last.txt") == hl.* ]] || fail "live chunk starts with a statement, not the file header" "$(head -1 "$sandbox/eval-last.txt")"
assert_not_contains "$eval_chunk" "-- " "live chunk carries no comments"
assert_contains "$eval_chunk" 'output = "DP-1", mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0' "untouched display declared explicitly"
assert_contains "$eval_chunk" 'output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 203' "changed display carries colour fields"
assert_contains "$(cat "$sandbox/systemd-run.log")" "revert --expired" "revert timer armed"
[[ ! -e $sandbox/state/candela-layout.lua ]] || fail "layout not persisted before keep"
pass "apply arms the timer and declares every display"

# ---- state while pending
state="$(run_cli "$sandbox" state)"
assert_eq "$(jq -r '.pending | type' <<<"$state")" "object" "state exposes pending"
assert_eq "$(jq -r '.displays[1].pendingConfig.cm' <<<"$state")" "hdr" "pending config attached per display"
pass "pending state"

# ---- chained apply keeps earlier pending fields
run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","sdr_max_luminance":250}]}' >/dev/null
eval_chunk="$(cat "$sandbox/eval-last.txt")"
assert_contains "$eval_chunk" 'cm = "hdr", sdr_max_luminance = 250' "chained apply merges onto pending"
pass "chained apply"

# ---- keep
: > "$sandbox/hyprctl.log"
out="$(run_cli "$sandbox" keep)"
assert_eq "$out" "kept" "keep reports kept"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after keep"
lua="$(cat "$sandbox/state/candela-layout.lua")"
assert_contains "$lua" "Generated by io.github.pushmotta.candela" "layout header"
assert_contains "$lua" 'hl.monitor({ output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 250 })' "layout carries kept fields"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", mode = "3840x2560@59.98", position = "0x0", scale = 1.6, transform = 0 })' "layout declares the other display"
assert_eq "$(jq -r '.displays["DP-2"].cm' "$sandbox/state/intent.json")" "hdr" "intent persisted"
assert_contains "$(cat "$sandbox/hyprctl.log")" "reload" "keep reloads"
pass "keep persists intent and layout"

# ---- revert drops pending and reloads
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
out="$(run_cli "$sandbox" revert)"
assert_eq "$out" "reverted" "revert reports"
[[ ! -e $sandbox/state/pending.json ]] || fail "pending cleared after revert"
assert_eq "$(jq -r '.displays["DP-1"].scale // "none"' "$sandbox/state/intent.json")" "none" "reverted change not in intent"
pass "revert"

# ---- the timer's own revert must not stop its own service before cleaning up
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
token="$(jq -r '.token' "$sandbox/state/pending.json")"
: > "$sandbox/systemctl.log"
out="$(run_cli "$sandbox" revert --expired --token "$token")"
assert_eq "$out" "reverted" "expired revert reports"
[[ ! -e $sandbox/state/pending.json ]] || fail "expired revert clears pending"
assert_not_contains "$(cat "$sandbox/systemctl.log")" "stop" "expired revert does not stop its own unit"
run_cli "$sandbox" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
: > "$sandbox/systemctl.log"
run_cli "$sandbox" revert >/dev/null
assert_contains "$(cat "$sandbox/systemctl.log")" "stop omarchy-candela-revert.timer" "interactive revert cancels the timer"
pass "expired revert survives its own timer unit"

# ---- apply --now persists immediately
out="$(run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-2","sdr_max_luminance":203}]}')"
assert_eq "$out" "kept" "apply --now keeps"
assert_eq "$(jq -r '.displays["DP-2"].sdr_max_luminance' "$sandbox/state/intent.json")" "203" "apply --now persisted"
pass "apply --now"

# ---- validation
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","cm":"bogus"}]}' 2>/dev/null; then fail "bad cm rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2;x","bitdepth":10}]}' 2>/dev/null; then fail "bad name rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","icc":"/tmp/a]==]b"}]}' 2>/dev/null; then fail "lua-breaking icc rejected"; fi
if run_cli "$sandbox" apply '{"displays":[{"name":"DP-2","evil":1}]}' 2>/dev/null; then fail "unknown key rejected"; fi
pass "validation rejects bad input"

# ---- disable + mirror + icc + global
# DP-2's kept intent still has cm:hdr from the tests above; move it to "auto"
# in the same change, since icc together with hdr is now rejected (6a).
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":false},{"name":"DP-2","cm":"auto","icc":"/home/p/My Profile.icc","vrr":1}],"global":{"cm_auto_hdr":0}}' >/dev/null
lua="$(cat "$sandbox/state/candela-layout.lua")"
assert_contains "$lua" 'hl.monitor({ output = "DP-1", disabled = true })' "disabled display rule"
assert_contains "$lua" 'icc = [==[/home/p/My Profile.icc]==]' "icc path as long string"
assert_contains "$lua" 'vrr = 1' "vrr written"
assert_contains "$lua" 'hl.config({ render = { cm_auto_hdr = 0 } })' "global auto-hdr written"
pass "disable, icc, vrr, global"

# ---- hdr shortcut
run_cli "$sandbox" apply --now '{"displays":[{"name":"DP-1","enabled":true}]}' >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1)"
assert_contains "$out" "pending" "hdr on is a timed apply"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_max_luminance' "$sandbox/state/pending.json")" "203" "hdr on anchors SDR white at 203"
assert_eq "$(jq -r '.intent.displays["DP-1"].sdr_min_luminance' "$sandbox/state/pending.json")" "0.2" "hdr on keeps Hyprland min when EDID says 0"
run_cli "$sandbox" revert >/dev/null
out="$(run_cli "$sandbox" hdr on --display DP-1 --sdr-white 9000 --now)"
assert_eq "$(jq -r '.displays["DP-1"].sdr_max_luminance' "$sandbox/state/intent.json")" "497" "SDR white clamped to max-average luminance"
run_cli "$sandbox" hdr off --display DP-1 --now >/dev/null
assert_eq "$(jq -r '.displays["DP-1"].cm' "$sandbox/state/intent.json")" "srgb" "hdr off returns to srgb"
assert_eq "$(jq -r '.displays["DP-1"] | has("sdr_max_luminance")' "$sandbox/state/intent.json")" "false" "hdr off clears SDR white"
pass "hdr shortcut"

# ---- icc list
out="$(run_cli "$sandbox" icc list)"
jq -e 'type == "array"' <<<"$out" >/dev/null || fail "icc list is a JSON array"
pass "icc list"

# ---- apply writes a transaction token, and the timer names it
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
token="$(jq -r '.token' "$sandbox2/state/pending.json")"
[[ -n $token && $token != "null" ]] || fail "pending.json carries a token" "$token"
assert_contains "$(cat "$sandbox2/systemd-run.log")" "revert --expired --token $token" "timer command line names the token"
pass "apply writes a transaction token and arms the timer with it"

# ---- a hyprctl rejection unwinds instead of leaving a dangling pending/timer
sandbox2="$(new_sandbox)"
if FAKE_HYPRCTL_EVAL_FAIL=1 run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' 2>/dev/null; then
  fail "apply exits non-zero when hyprctl rejects the eval"
fi
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json survives a failed apply"
assert_contains "$(cat "$sandbox2/systemctl.log")" "stop" "unwind stops the timer"
assert_contains "$(tail -1 "$sandbox2/hyprctl.log")" "reload" "unwind reloads to restore the last kept config"
pass "a failing hyprctl eval unwinds the pending apply"

# ---- revert --expired only acts when the token matches a still-pending change
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" revert --expired --token "not-the-real-token")"
assert_eq "$out" "nothing to revert" "mismatched token does nothing"
[[ -s $sandbox2/state/pending.json ]] || fail "mismatched token leaves pending.json in place"
[[ -z "$(cat "$sandbox2/hyprctl.log")" ]] || fail "mismatched token does not reload" "$(cat "$sandbox2/hyprctl.log")"

real_token="$(jq -r '.token' "$sandbox2/state/pending.json")"
out="$(run_cli "$sandbox2" revert --expired --token "$real_token")"
assert_eq "$out" "reverted" "matching token reverts"
[[ ! -e $sandbox2/state/pending.json ]] || fail "matching token clears pending.json"
assert_contains "$(cat "$sandbox2/hyprctl.log")" "reload" "matching token reloads"

: > "$sandbox2/hyprctl.log"
out="$(run_cli "$sandbox2" revert --expired --token "$real_token")"
assert_eq "$out" "nothing to revert" "no pending: expired revert does nothing"
[[ -z "$(cat "$sandbox2/hyprctl.log")" ]] || fail "no pending: expired revert does not reload" "$(cat "$sandbox2/hyprctl.log")"
pass "revert --expired only acts on a matching token"

# ---- top-level keys: only displays/global are accepted, and one must be present
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" apply '{"unexpected":true}' 2>/dev/null; then fail "unknown top-level key rejected"; fi
if run_cli "$sandbox2" apply '{}' 2>/dev/null; then fail "empty change rejected"; fi
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json armed by a rejected top-level change"
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":1.8}]}')"
assert_contains "$out" "pending" "a valid change still applies"
pass "top-level keys are validated"

# ---- colour invariants apply to the merged display (existing intent + change)
sandbox2="$(new_sandbox)"
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","icc":"/tmp/a.icc","cm":"hdr"}]}' 2>/dev/null; then
  fail "icc together with cm hdr rejected"
fi
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","icc":"/tmp/a.icc","cm":"hdredid"}]}' 2>/dev/null; then
  fail "icc together with cm hdredid rejected"
fi
# supports_hdr follows Hyprland's own convention: -1 forces HDR off, 0 is
# auto/EDID (the default, must NOT block hdr), 1 forces it on.
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","supports_hdr":-1,"cm":"hdr"}]}' 2>/dev/null; then
  fail "supports_hdr forced off (-1) together with cm hdr rejected"
fi
out="$(run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","supports_hdr":0,"cm":"hdr"}]}')"
assert_contains "$out" "pending" "supports_hdr 0 (auto/EDID default) does not block hdr"
run_cli "$sandbox2" revert >/dev/null
# kept intent already has cm:hdr; a later change that only sets icc must be
# checked against that merged state, not just the change in isolation.
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","icc":"/tmp/a.icc"}]}' 2>/dev/null; then
  fail "icc rejected against a kept cm:hdr intent (merged-state check)"
fi
pass "colour invariants apply to the merged display, not just the change"

# ---- apply --now reloads and checks configerrors, like keep
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
log="$(cat "$sandbox2/hyprctl.log")"
assert_contains "$log" "reload" "apply --now reloads"
assert_contains "$log" "configerrors" "apply --now checks configerrors"
pass "apply --now validates the written Lua like keep does"

# ---- structural check: every display key merge_intent accepts must reach
# generate_lua's output, or the timer's plain `hyprctl reload` cannot
# reconstruct it after a revert. "enabled" is the one exception: Hyprland's
# hl.monitor has no such key, so it is folded into the presence/absence of
# "disabled" instead of being written verbatim (see the loop's note below).
sandbox2="$(new_sandbox)"
change='{"displays":[{"name":"DP-2",
  "mode":"preferred","position":"100x50","scale":1.5,"transform":1,
  "vrr":1,"enabled":true,"mirror":"DP-1","bitdepth":10,"cm":"auto",
  "sdr_eotf":"srgb","sdrbrightness":1.2,"sdrsaturation":1.1,
  "sdr_min_luminance":0.2,"sdr_max_luminance":203,
  "min_luminance":0.05,"max_luminance":500,"max_avg_luminance":450,
  "icc":"/home/p/profile.icc","supports_hdr":1,"supports_wide_color":1
}]}'
run_cli "$sandbox2" apply --now "$change" >/dev/null
lua="$(cat "$sandbox2/state/candela-layout.lua")"
for key in mode position scale transform vrr mirror bitdepth cm sdr_eotf \
           sdrbrightness sdrsaturation sdr_min_luminance sdr_max_luminance \
           max_avg_luminance icc supports_hdr supports_wide_color; do
  assert_contains "$lua" "$key = " "generated Lua emits $key"
done
# min_luminance/max_luminance searched with a leading ", " so the match can't
# land inside sdr_min_luminance/sdr_max_luminance, which contain them as a substring.
assert_contains "$lua" ", min_luminance = " "generated Lua emits min_luminance distinctly from sdr_min_luminance"
assert_contains "$lua" ", max_luminance = " "generated Lua emits max_luminance distinctly from sdr_max_luminance"
pass "every accepted display key reaches the generated Lua (enabled excluded: see note above)"

# ---- the preview lives in a toggles file, loaded after the layout
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
[[ -s $sandbox2/state/candela-pending.lua ]] || fail "pending toggles file written on a timed apply"
assert_contains "$(cat "$sandbox2/state/candela-pending.lua")" 'output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6, transform = 0, bitdepth = 10, cm = "hdr", sdr_max_luminance = 203' "pending file carries the change"
assert_contains "$(head -1 "$sandbox2/state/candela-pending.lua")" "Generated by" "pending file carries the header"
# A reload from anywhere else (a theme change, Omarchy's clamshell script)
# re-reads the toggles directory: the preview stays on the glass.
PATH="$sandbox2/bin:$PATH" hyprctl reload >/dev/null
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .colorManagementPreset')" "hdr" "a foreign reload keeps the preview"
run_cli "$sandbox2" revert >/dev/null
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "revert removes the pending toggles file"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .colorManagementPreset')" "srgb" "revert returns the display to the kept state"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","bitdepth":10,"cm":"hdr","sdr_max_luminance":203}]}' >/dev/null
run_cli "$sandbox2" keep >/dev/null
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "keep removes the pending toggles file"
pass "the preview is a toggles file: a foreign reload keeps it, keep and revert remove it"

# ---- readback: a change the compositor did not land on is undone, not left pending
sandbox2="$(new_sandbox)"
if out="$(FAKE_HYPRCTL_IGNORE_SCALE=1 run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","scale":2}]}' 2>&1)"; then
  fail "apply exits non-zero when the readback disagrees"
fi
assert_contains "$out" "scale" "the mismatch names the field"
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json survives a failed readback"
[[ ! -e $sandbox2/state/candela-pending.lua ]] || fail "no pending toggles file survives a failed readback"
assert_contains "$(tail -1 "$sandbox2/hyprctl.log")" "reload" "a failed readback unwinds with a reload"
pass "a change the compositor did not land on is undone"

# ---- keep proves the layout file ran on reload
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","scale":2}]}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'omarchy_candela_layout_probe = "' "layout carries a load probe"
run_cli "$sandbox2" apply '{"displays":[{"name":"DP-2","scale":1.6}]}' >/dev/null
if out="$(FAKE_HYPRCTL_TOGGLES_NOT_LOADED=1 run_cli "$sandbox2" keep 2>&1)"; then
  fail "keep fails when the layout file did not run"
fi
assert_contains "$out" "did not run" "keep says the layout file did not run"
assert_contains "$out" "doctor" "keep points at doctor"
pass "keep proves the layout file ran"

# ---- a display switched off keeps its geometry and comes back where it was
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
assert_eq "$(jq -r '.displays["DP-2"].position' "$sandbox2/state/intent.json")" "2400x0" "position remembered at switch-off"
assert_eq "$(jq -r '.displays["DP-2"].scale' "$sandbox2/state/intent.json")" "1.6" "scale remembered at switch-off"
assert_eq "$(jq -r '.displays["DP-2"].mode' "$sandbox2/state/intent.json")" "3840x2560@59.98" "mode remembered at switch-off"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .disabled')" "true" "display is off"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":true}]}' >/dev/null
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "DP-2", mode = "3840x2560@59.98", position = "2400x0", scale = 1.6' "a re-enabled display returns to its old place, not 0x0"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-2") | .x')" "2400" "and the compositor agrees"
pass "switching a display off remembers its geometry"

# ---- the last enabled display cannot be switched off from the CLI either
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","enabled":false}]}' >/dev/null
if run_cli "$sandbox2" apply '{"displays":[{"name":"DP-1","enabled":false}]}' 2>/dev/null; then fail "switching off the last display rejected"; fi
[[ ! -e $sandbox2/state/pending.json ]] || fail "no pending.json armed by a rejected switch-off"
pass "the last enabled display stays on"

# ---- recover: every display off, the built-in panel (else the first) comes back
sandbox2="$(new_sandbox)"
jq 'map(.disabled = true | .width = 0 | .height = 0)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered DP-1" "recover names the display it switched on"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "DP-1") | .disabled')" "false" "DP-1 is on after recover"
assert_eq "$(run_cli "$sandbox2" recover)" "nothing to recover" "recover is a no-op with a display on"
sandbox2="$(new_sandbox laptop)"
jq 'map(.disabled = true | .width = 0 | .height = 0)' "$sandbox2/monitors.json" > "$sandbox2/m.tmp" && mv "$sandbox2/m.tmp" "$sandbox2/monitors.json"
assert_eq "$(run_cli "$sandbox2" recover)" "recovered eDP-1" "recover prefers the built-in panel"
pass "recover"

# ---- the built-in panel is switched off through Omarchy's own toggle
sandbox2="$(new_sandbox laptop)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","enabled":false}]}' >/dev/null
flag="$sandbox2/state/internal-monitor-disable.lua"
[[ -f $flag ]] || fail "Omarchy's internal-monitor-disable flag written"
assert_eq "$(cat "$flag")" 'hl.monitor({ output = "eDP-1", disabled = true })' "flag has Omarchy's own content"
assert_not_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "eDP-1", disabled' "layout carries no disable rule of its own for the panel"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" "internal-monitor-disable" "layout says where the panel's off state lives"
assert_eq "$(jq -r '.displays["eDP-1"] | has("enabled")' "$sandbox2/state/intent.json")" "false" "intent does not store enabled for the panel"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "eDP-1") | .disabled')" "true" "panel is off"
# A timed re-enable removes the flag; reverting puts it back.
run_cli "$sandbox2" apply '{"displays":[{"name":"eDP-1","enabled":true}]}' >/dev/null
[[ ! -e $flag ]] || fail "a timed re-enable removes the flag"
assert_eq "$(jq -r '.internalFlagBefore.present' "$sandbox2/state/pending.json")" "true" "pending remembers the flag was there"
run_cli "$sandbox2" revert >/dev/null
[[ -f $flag ]] || fail "revert restores the flag"
assert_eq "$(PATH="$sandbox2/bin:$PATH" hyprctl monitors all -j | jq -r '.[] | select(.name == "eDP-1") | .disabled')" "true" "panel is off again after revert"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","enabled":true}]}' >/dev/null
[[ ! -e $flag ]] || fail "a kept re-enable removes the flag"
assert_contains "$(cat "$sandbox2/state/candela-layout.lua")" 'output = "eDP-1", mode = "2880x1800@60", position = "0x0", scale = 2' "the re-enabled panel has a full rule again"
pass "the built-in panel's off state is Omarchy's flag"

# ---- the panel's kept scale is where Omarchy's clamshell script looks for it
sandbox2="$(new_sandbox laptop)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"eDP-1","scale":1.5}]}' >/dev/null
assert_eq "$(cat "$sandbox2/state/internal-monitor-scale")" "1.5" "internal-monitor-scale written on keep"
sandbox2="$(new_sandbox)"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-1","scale":2}]}' >/dev/null
[[ ! -e $sandbox2/state/internal-monitor-scale ]] || fail "no scale file without a built-in panel"
pass "internal-monitor-scale follows the kept scale"

# ---- doctor
sandbox2="$(new_sandbox)"
mkdir -p "$sandbox2/.config/hypr"
printf 'require("default.hypr.omarchy")\nrequire("hypr.monitors")\nrequire("default.hypr.toggles")\n' > "$sandbox2/.config/hypr/hyprland.lua"
printf 'local omarchy_monitor_scale = "auto"\nhl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })\n' > "$sandbox2/.config/hypr/monitors.lua"
run_cli "$sandbox2" apply --now '{"displays":[{"name":"DP-2","scale":2}]}' >/dev/null
out="$(run_cli "$sandbox2" doctor)" || fail "doctor exits 0 on a healthy sandbox" "$out"
assert_contains "$out" "ok    Hyprland ran" "doctor confirms the layout ran"
assert_contains "$out" "toggles directory" "doctor checks the toggles require"
assert_not_contains "$out" "FAIL" "doctor reports no failure"
sed -i '/default.hypr.toggles/d' "$sandbox2/.config/hypr/hyprland.lua"
if out="$(run_cli "$sandbox2" doctor)"; then fail "doctor exits 1 when the toggles are not required"; fi
assert_contains "$out" "FAIL  $sandbox2/.config/hypr/hyprland.lua does not require" "doctor names the missing require"
pass "doctor"
